export interface TradePolicy {
  edgeRequired: number;
  maxEdge: number;
  evMaxEdge: number;
  depthHeadroomFraction: number;
  maxSpread: number;
  orderbookFreshnessMs: number;
  topOfBookStabilityMs: number;
  maxOpenInventorySeconds: number;
  rejectDelayed: boolean;
  strategyMode: 'near_zero_risk' | 'standard';
  signalMode: 'near_zero' | 'ev' | 'both';
  requireFreshBook: boolean;
  maxBookStalenessMs: number;
  maxDecisionLatencyMs: number;
  maxDelayedAckRate: number;
  minPairedFillRate: number;
  minEdgeTicks: number;
  depthBufferMultiplier: number;
  entrySlippageToleranceBps: number;
  minDepthLevels: number;
  maxOrdersPerMinute: number;
  maxOrderToTradeRatio: number;
  orderVelocityWindowMs: number;
  orderToTradeWindowMs: number;
  priceBandBps: number;
  maxLegSkewMs: number;
  submitTimeoutMs: number;
  ackTimeoutMs: number;
  fillTimeoutMs: number;
  cancelTimeoutMs: number;
  fallbackTickSize: number;
  fallbackMinOrderSize: number;
  nearZeroFeeBps: number;
  evEdgeRequired: number;
  evFeeBps: number;
  evConfidenceMin: number;
  evConfidenceMinFloor: number;
  evMaxPerMarketNotional: number;
  evMaxPortfolioNotional: number;
  evCooldownSeconds: number;
  evModelMode: 'baseline' | 'hybrid' | 'llm_only';
  evModelRefreshMinutes: number;
  evCalibrationMethod: 'sigmoid' | 'isotonic' | 'temperature';
  evModelConfidenceFloor: number;
  evWebSearchProviderPolicy: 'exa_only' | 'serper_only' | 'serper_exa' | 'gdelt_serper_exa';
  evWebSearchRefreshMinutes: number;
  evWebSearchExaEnabled: boolean;
  evWebSearchFirecrawlEnabled: boolean;
  evWebSearchSerperEnabled: boolean;
  evWebSearchGdeltEnabled: boolean;
  evWebSearchExaFallbackEnabled: boolean;
  evWebSearchLookbackDays: number;
  evWebSearchMaxResults: number;
  evWebSearchCacheTtlSeconds: number;
  evWebSearchMaxConcurrency: number;
  evWebSearchDefaultContentBudget: number;
  evWebSearchHighPriorityContentBudget: number;
  evWebSearchDefaultQueryMode: 'base_only' | 'base_plus_one' | 'base_plus_two';
  evWebSearchNearResolutionMinutes: number;
  evWebSearchPriceMoveTriggerBps: number;
  evWebSearchOfficialDomainRequired: boolean;
  evWebSearchGdeltRefreshMinutes: number;
  evWebSearchGdeltTriggerThreshold: number;
  evWebSearchExaInlineContentsEnabled: boolean;
  evWebSearchExaInlineContentsMaxResults: number;
  evWebSearchFirecrawlMaxDepth: number;
  evWebSearchFirecrawlMaxPages: number;
  fwDependencyMode: 'deterministic' | 'llm' | 'hybrid';
  fwDependencyHybridMerge: 'consensus' | 'union';
  fwDependencyMinConfidence: number;
  fwDependencyMaxEdgesPerMarket: number;
  fwRelationCatalogSemanticBatchEnabled: boolean;
  fwRelationCatalogMinConfidence: number;
  fwRelationCatalogMaxEdgesPerMarket: number;
  fwRelationCandidatesPerMarketMax: number;
  fwRelationCandidatesTotalMax: number;
  fwUniverseMode: 'broad_rotation' | 'dependency_cohort';
  fwDependencyCacheTtlMs: number;
  fwDependencyCacheGraceMs: number;
  fwDependencyCacheMaxEntries: number;
  fwDependencyBackoffInvalidMs: number;
  fwDependencyBackoffTimeoutMs: number;
  fwDependencyBackoffErrorMs: number;
  fwOracleTimeLimitMs: number;
  fwOracleMaxConcurrency: number;
  fwMaxIterations: number;
  fwMaxLoopRuntimeMs: number;
  fwGapAbsTolerance: number;
  fwGapRelTolerance: number;
  fwRequireConverged: boolean;
  fwContractionInitialEpsilon: number;
  fwContractionDecay: number;
  fwContractionMinEpsilon: number;
  fwStallIterationLimit: number;
  fwActiveSetMaxVertices: number;
  fwHullSolveMaxIterations: number;
  fwHullSolveTolerance: number;
  fwMaxProjectionAgeMs: number;
  fwSlippageToleranceBps: number;
  fwExecutionRiskBufferBps: number;
  fwMinEdgeThreshold: number;
  fwSelectionWeightFloor: number;
  fwSelectionTopK: number;
  fwMaxPerMarketNotional: number;
  fwMaxPortfolioNotional: number;
  fwBasketMinMarkets: number;
  fwBasketMaxMarkets: number;
  fwBasketExecutionMode: 'batch_best_effort' | 'sequential_failfast';
}


export const DEFAULT_TRADE_POLICY: TradePolicy = {
  edgeRequired: 0.03,
  maxEdge: 0.05,
  evMaxEdge: 0.05,
  depthHeadroomFraction: 0.25,
  maxSpread: 0.05,
  orderbookFreshnessMs: 15000,
  topOfBookStabilityMs: 250,
  maxOpenInventorySeconds: 2,
  rejectDelayed: true,
  strategyMode: 'near_zero_risk',
  signalMode: 'both',
  requireFreshBook: true,
  maxBookStalenessMs: 15000,
  maxDecisionLatencyMs: 250,
  maxDelayedAckRate: 0.001,
  minPairedFillRate: 0.999,
  minEdgeTicks: 3,
  depthBufferMultiplier: 1.5,
  entrySlippageToleranceBps: 50,
  minDepthLevels: 3,
  maxOrdersPerMinute: 60,
  maxOrderToTradeRatio: 10,
  orderVelocityWindowMs: 60000,
  orderToTradeWindowMs: 600000,
  priceBandBps: 500,
  maxLegSkewMs: 100,
  submitTimeoutMs: 2000,
  ackTimeoutMs: 2500,
  fillTimeoutMs: 5000,
  cancelTimeoutMs: 2000,
  fallbackTickSize: 0.01,
  fallbackMinOrderSize: 0.001,
  nearZeroFeeBps: 0,
  evEdgeRequired: 0.01,
  evFeeBps: 0,
  evConfidenceMin: 0.6,
  evConfidenceMinFloor: 0.4,
  evMaxPerMarketNotional: 100,
  evMaxPortfolioNotional: 300,
  evCooldownSeconds: 120,
  evModelMode: 'hybrid',
  evModelRefreshMinutes: 60,
  evCalibrationMethod: 'sigmoid',
  evModelConfidenceFloor: 0.55,
  evWebSearchProviderPolicy: 'gdelt_serper_exa',
  evWebSearchRefreshMinutes: 30,
  evWebSearchExaEnabled: true,
  evWebSearchFirecrawlEnabled: false,
  evWebSearchSerperEnabled: true,
  evWebSearchGdeltEnabled: true,
  evWebSearchExaFallbackEnabled: true,
  evWebSearchLookbackDays: 7,
  evWebSearchMaxResults: 10,
  evWebSearchCacheTtlSeconds: 7200,
  evWebSearchMaxConcurrency: 3,
  evWebSearchDefaultContentBudget: 3,
  evWebSearchHighPriorityContentBudget: 5,
  evWebSearchDefaultQueryMode: 'base_plus_one',
  evWebSearchNearResolutionMinutes: 240,
  evWebSearchPriceMoveTriggerBps: 500,
  evWebSearchOfficialDomainRequired: true,
  evWebSearchGdeltRefreshMinutes: 15,
  evWebSearchGdeltTriggerThreshold: 0.45,
  evWebSearchExaInlineContentsEnabled: true,
  evWebSearchExaInlineContentsMaxResults: 10,
  evWebSearchFirecrawlMaxDepth: 2,
  evWebSearchFirecrawlMaxPages: 10,
  fwDependencyMode: 'hybrid',
  fwDependencyHybridMerge: 'consensus',
  fwDependencyMinConfidence: 0.6,
  fwDependencyMaxEdgesPerMarket: 8,
  fwRelationCatalogSemanticBatchEnabled: false,
  fwRelationCatalogMinConfidence: 0.6,
  fwRelationCatalogMaxEdgesPerMarket: 8,
  fwRelationCandidatesPerMarketMax: 4,
  fwRelationCandidatesTotalMax: 20,
  fwUniverseMode: 'broad_rotation',
  fwDependencyCacheTtlMs: 120000,
  fwDependencyCacheGraceMs: 30000,
  fwDependencyCacheMaxEntries: 128,
  fwDependencyBackoffInvalidMs: 5000,
  fwDependencyBackoffTimeoutMs: 10000,
  fwDependencyBackoffErrorMs: 15000,
  fwOracleTimeLimitMs: 120,
  fwOracleMaxConcurrency: 4,
  fwMaxIterations: 12,
  fwMaxLoopRuntimeMs: 350,
  fwGapAbsTolerance: 0.0005,
  fwGapRelTolerance: 0.05,
  fwRequireConverged: true,
  fwContractionInitialEpsilon: 0.1,
  fwContractionDecay: 0.5,
  fwContractionMinEpsilon: 0.01,
  fwStallIterationLimit: 2,
  fwActiveSetMaxVertices: 12,
  fwHullSolveMaxIterations: 60,
  fwHullSolveTolerance: 0.000001,
  fwMaxProjectionAgeMs: 250,
  fwSlippageToleranceBps: 60,
  fwExecutionRiskBufferBps: 10,
  fwMinEdgeThreshold: 0.003,
  fwSelectionWeightFloor: 0.5,
  fwSelectionTopK: 0,
  fwMaxPerMarketNotional: 75,
  fwMaxPortfolioNotional: 200,
  fwBasketMinMarkets: 2,
  fwBasketMaxMarkets: 4,
  fwBasketExecutionMode: 'sequential_failfast'
};

export function isNearZeroRiskMode(policy: TradePolicy): boolean {
  return policy.strategyMode === 'near_zero_risk';
}
