import { z } from 'zod';

import { envBoolean, llmEndpointSchema } from './shared.js';

export const llmEnvShape = {
  LLM_ENABLED: envBoolean(true),
  LLM_DATA_EXPORT_ENABLED: envBoolean(true),
  LLM_PRIMARY_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('opencode-zen'),
  LLM_FALLBACK_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('openrouter'),
  LLM_PRIMARY_BASE_URL: z.string().optional(),
  LLM_FALLBACK_BASE_URL: z.string().optional(),
  LLM_PRIMARY_API_KEY: z.string().optional(),
  LLM_FALLBACK_API_KEY: z.string().optional(),
  LLM_FALLBACK_ENABLED: envBoolean(false),
  LLM_PRIMARY_RETRY_COUNT: z.coerce.number().int().min(0).default(1),
  LLM_OPENROUTER_SORT: z.enum(['latency', 'price', 'throughput']).default('latency'),
  LLM_OPENROUTER_ALLOW_FALLBACKS: envBoolean(true),
  LLM_OPENROUTER_HTTP_REFERER: z.string().optional(),
  LLM_OPENROUTER_X_TITLE: z.string().optional(),
  LLM_TIMEOUT_MS: z.coerce.number().int().positive().default(10000),
  LLM_MAX_RETRIES: z.coerce.number().int().min(0).default(1),
  LLM_CB_FAILURE_THRESHOLD: z.coerce.number().int().positive().default(5),
  LLM_CB_COOLDOWN_MS: z.coerce.number().int().positive().default(30000),
  LLM_CB_HALF_OPEN_SUCCESSES: z.coerce.number().int().positive().default(2),
  LLM_EXECUTION_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('opencode-zen'),
  LLM_EXECUTION_MODEL: z.string().default('kimi-k2.5'),
  LLM_EXECUTION_MODE: z.enum(['disabled', 'shadow', 'advisory']).default('advisory'),
  LLM_EXECUTION_TIMEOUT_MS: z.coerce.number().int().positive().default(12000),
  LLM_EXECUTION_MODEL_BACKUP: z.string().optional(),
  LLM_EXECUTION_ENDPOINT_BACKUP: llmEndpointSchema,
  LLM_EXECUTION_FALLBACK_PROVIDER_MODEL: z.string().optional(),
  LLM_RISK_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('opencode-zen'),
  LLM_RISK_MODEL: z.string().default('minimax-m2.1'),
  LLM_RISK_MODE: z.enum(['disabled', 'shadow', 'advisory']).default('advisory'),
  LLM_RISK_TIMEOUT_MS: z.coerce.number().int().positive().default(12000),
  LLM_RISK_MODEL_BACKUP: z.string().optional(),
  LLM_RISK_ENDPOINT_BACKUP: llmEndpointSchema,
  LLM_RISK_FALLBACK_PROVIDER_MODEL: z.string().optional(),
  LLM_SCANNER_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('opencode-zen'),
  LLM_SCANNER_MODEL: z.string().default('glm-4.7'),
  LLM_SCANNER_MODE: z.enum(['disabled', 'shadow', 'advisory']).default('advisory'),
  LLM_SCANNER_TIMEOUT_MS: z.coerce.number().int().positive().default(12000),
  LLM_SCANNER_SCORE_TOP_N: z.coerce.number().int().min(0).default(20),
  LLM_SCANNER_SCORE_CONCURRENCY: z.coerce.number().int().min(1).default(3),
  LLM_SCANNER_SHADOW_MIN_INTERVAL_MS: z.coerce.number().int().min(0).default(500),
  LLM_SCANNER_MODEL_BACKUP: z.string().optional(),
  LLM_SCANNER_ENDPOINT_BACKUP: llmEndpointSchema,
  LLM_SCANNER_FALLBACK_PROVIDER_MODEL: z.string().optional(),
  LLM_LEARNING_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('opencode-zen'),
  LLM_LEARNING_MODEL: z.string().default('kimi-k2.5'),
  LLM_LEARNING_MODE: z.enum(['disabled', 'active']).default('active'),
  LLM_LEARNING_TIMEOUT_MS: z.coerce.number().int().positive().default(20000),
  LLM_LEARNING_MODEL_BACKUP: z.string().optional(),
  LLM_LEARNING_ENDPOINT_BACKUP: llmEndpointSchema,
  LLM_LEARNING_FALLBACK_PROVIDER_MODEL: z.string().default('qwen/qwen3-coder-next'),
  LLM_PORTFOLIO_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('opencode-zen'),
  LLM_PORTFOLIO_MODEL: z.string().default('minimax-m2.1'),
  LLM_PORTFOLIO_MODE: z.enum(['disabled', 'advisory']).default('advisory'),
  LLM_PORTFOLIO_TIMEOUT_MS: z.coerce.number().int().positive().default(20000),
  LLM_PORTFOLIO_MODEL_BACKUP: z.string().optional(),
  LLM_PORTFOLIO_ENDPOINT_BACKUP: llmEndpointSchema,
  LLM_PORTFOLIO_FALLBACK_PROVIDER_MODEL: z.string().optional(),
  LLM_MARKETDATA_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('opencode-zen'),
  LLM_MARKETDATA_MODEL: z.string().default('glm-4.7'),
  LLM_MARKETDATA_MODE: z.enum(['disabled', 'advisory']).default('advisory'),
  LLM_MARKETDATA_TIMEOUT_MS: z.coerce.number().int().positive().default(20000),
  LLM_MARKETDATA_MODEL_BACKUP: z.string().optional(),
  LLM_MARKETDATA_ENDPOINT_BACKUP: llmEndpointSchema,
  LLM_MARKETDATA_FALLBACK_PROVIDER_MODEL: z.string().optional(),
  LLM_OPS_PROVIDER: z.enum(['opencode-zen', 'openrouter']).default('opencode-zen'),
  LLM_OPS_MODEL: z.string().default('glm-4.7'),
  LLM_OPS_MODE: z.enum(['disabled', 'advisory']).default('advisory'),
  LLM_OPS_TIMEOUT_MS: z.coerce.number().int().positive().default(12000),
  LLM_OPS_MODEL_BACKUP: z.string().optional(),
  LLM_OPS_ENDPOINT_BACKUP: llmEndpointSchema,
  LLM_OPS_FALLBACK_PROVIDER_MODEL: z.string().optional()
};
