import { z } from 'zod';

export const polymarketEnvShape = {
  POLYMARKET_CLOB_BASE_URL: z.string().optional(),
  POLYMARKET_CLOB_TIMEOUT_MS: z.coerce.number().int().positive().default(8000),
  POLYMARKET_CLOB_RATE_LIMIT_PER_SEC: z.coerce.number().int().positive().default(300),
  POLYMARKET_CLOB_RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(1000),
  POLYMARKET_CLOB_ORDER_PATH: z.string().default('/orders'),
  POLYMARKET_CLOB_BATCH_ORDER_PATH: z.string().default('/orders'),
  POLYMARKET_CLOB_CANCEL_ORDER_PATH: z.string().default('/order'),
  POLYMARKET_CLOB_CANCEL_ORDERS_PATH: z.string().default('/orders'),
  POLYMARKET_CLOB_CANCEL_ALL_PATH: z.string().default('/cancel-all'),
  POLYMARKET_CLOB_CANCEL_MARKET_ORDERS_PATH: z.string().default('/cancel-market-orders'),
  POLYMARKET_CLOB_ACTIVE_ORDERS_PATH: z.string().default('/data/orders'),
  POLYMARKET_CLOB_RETRY_MAX_RETRIES: z.coerce.number().int().positive().default(3),
  POLYMARKET_CLOB_RETRY_BASE_DELAY_MS: z.coerce.number().int().positive().default(250),
  POLYMARKET_CLOB_RETRY_MAX_DELAY_MS: z.coerce.number().int().positive().default(2000),
  POLYMARKET_WS_URL: z.string().default('wss://ws-subscriptions-clob.polymarket.com/ws/market'),
  POLYMARKET_USER_WS_URL: z.string().default('wss://ws-subscriptions-clob.polymarket.com/ws/user'),
  POLYMARKET_WS_HEARTBEAT_MS: z.coerce.number().int().positive().default(10000),
  POLYMARKET_WS_RECONNECT_BASE_MS: z.coerce.number().int().positive().default(250),
  POLYMARKET_WS_RECONNECT_MAX_MS: z.coerce.number().int().positive().default(30000),
  POLYMARKET_WS_RECONNECT_JITTER_PCT: z.coerce.number().min(0).max(1).default(0.2),
  POLYMARKET_API_KEY: z.string().optional(),
  POLYMARKET_API_SECRET: z.string().optional(),
  POLYMARKET_PASSPHRASE: z.string().optional(),
  POLYMARKET_DATA_API_BASE_URL: z.string().optional(),
  POLYMARKET_DATA_API_POSITIONS_PATH: z.string().default('/positions'),
  POLYMARKET_DATA_API_TIMEOUT_MS: z.coerce.number().int().positive().default(8000),
  POLYMARKET_DATA_API_RATE_LIMIT_PER_SEC: z.coerce.number().int().positive().default(300),
  POLYMARKET_DATA_API_RATE_LIMIT_WINDOW_MS: z.coerce.number().int().positive().default(1000),
  POLYMARKET_DATA_API_RETRY_MAX_RETRIES: z.coerce.number().int().positive().default(3),
  POLYMARKET_DATA_API_RETRY_BASE_DELAY_MS: z.coerce.number().int().positive().default(250),
  POLYMARKET_DATA_API_RETRY_MAX_DELAY_MS: z.coerce.number().int().positive().default(2000),
  POLYMARKET_POSITIONS_USER: z.string().optional(),
  POLYMARKET_POSITIONS_SIZE_THRESHOLD: z.coerce.number().min(0).default(0),
  POLYMARKET_POSITIONS_LIMIT: z.coerce.number().int().min(1).max(500).default(200),
  POLYMARKET_POSITIONS_OFFSET: z.coerce.number().int().min(0).max(10000).default(0),
  KALSHI_API_KEY_ID: z.string().optional(),
  KALSHI_PRIVATE_KEY_PEM: z.string().optional(),
  KALSHI_PRIVATE_KEY_PATH: z.string().optional(),
  POLYMARKET_L1_PRIVATE_KEY: z.string().optional(),
  POLYMARKET_L1_NONCE: z.coerce.number().int().min(0).optional()
};
